### ISSUE TITLE
Clicking on an empty directory in the workspace view throws an exception

### ISSUE THREAD

**Issue by madwort** [opensafely-core/airlock#260]
Using a url to navigate to an empty directory displays correctly, e.g. http://localhost:8000/workspaces/view/example-workspace/sub_dir_empty/ but navigating using the links in browser throws an exception. I assume this is an HTMX thing... 

```
<h1>IsADirectoryError
       at /workspaces/view/example-workspace/sub_dir_empty</h1>
  <pre class="exception_value">[Errno 21] Is a directory: '/Users/tom/Documents/bennett-institute/airlock/workdir/workspaces/example-workspace/sub_dir_empty'</pre>
  
Request Method: | GET
-- | --
http://localhost:8000/workspaces/view/example-workspace/sub_dir_empty
5.0.4
IsADirectoryError
[Errno 21] Is a directory: '/Users/tom/Documents/bennett-institute/airlock/workdir/workspaces/example-workspace/sub_dir_empty'
/Users/tom/.pyenv/versions/3.11.2/lib/python3.11/pathlib.py, line 1044, in open
airlock.views.workspace.workspace_view
/Users/tom/Documents/bennett-institute/airlock/.venv/bin/python
3.11.2
['/Users/tom/Documents/bennett-institute/airlock',  '/Users/tom/.pyenv/versions/3.11.2/lib/python311.zip',  '/Users/tom/.pyenv/versions/3.11.2/lib/python3.11',  '/Users/tom/.pyenv/versions/3.11.2/lib/python3.11/lib-dynload',  '/Users/tom/Documents/bennett-institute/airlock/.venv/lib/python3.11/site-packages']
Fri, 19 Apr 2024 10:33:23 +0000


```

**Comment by madwort** [comment]
here's the same thing from the test-backend
```
airlock    | /opt/venv/lib/python3.11/site-packages/django/template/base.py:925: UserWarning: Exception while resolving variable 'contents_url' in template 'file_browser/contents.html'.
airlock    |   logger.debug(
airlock    | Internal Server Error: /workspaces/view/benbc-test/empty_subdir
airlock    | Traceback (most recent call last):
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
airlock    |     response = get_response(request)
airlock    |                ^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
airlock    |     response = response.render()
airlock    |                ^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
airlock    |     self.content = self.rendered_content
airlock    |                    ^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
airlock    |     return template.render(context, self._request)
airlock    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
airlock    |     return self.template.render(context)
airlock    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
airlock    |     return self._render(context)
airlock    |            ^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
airlock    |     return self.nodelist.render(context)
airlock    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
airlock    |     return SafeString("".join([node.render_annotated(context) for node in self]))
airlock    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
airlock    |     return SafeString("".join([node.render_annotated(context) for node in self]))
airlock    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
airlock    |     return self.render(context)
airlock    |            ^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
airlock    |     return nodelist.render(context)
airlock    |            ^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
airlock    |     return SafeString("".join([node.render_annotated(context) for node in self]))
airlock    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
airlock    |     return SafeString("".join([node.render_annotated(context) for node in self]))
airlock    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
airlock    |     return self.render(context)
airlock    |            ^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/slippers/templatetags/slippers.py", line 270, in render
airlock    |     fragment = self.nodelist.render(context) if self.nodelist else ""
airlock    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
airlock    |     return SafeString("".join([node.render_annotated(context) for node in self]))
airlock    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
airlock    |     return SafeString("".join([node.render_annotated(context) for node in self]))
airlock    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
airlock    |     return self.render(context)
airlock    |            ^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/slippers/templatetags/slippers.py", line 98, in render
airlock    |     attributes = {
airlock    |                  ^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/slippers/templatetags/slippers.py", line 99, in <dictcomp>
airlock    |     key: value.resolve(context) for key, value in self.raw_attributes.items()
airlock    |          ^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 710, in resolve
airlock    |     obj = self.var.resolve(context)
airlock    |           ^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 842, in resolve
airlock    |     value = self._resolve_lookup(context)
airlock    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 909, in _resolve_lookup
airlock    |     current = current()
airlock    |               ^^^^^^^^^
airlock    |   File "/app/airlock/file_browser_api.py", line 88, in contents_url
airlock    |     return self.container.get_contents_url(self.relpath, download=download)
airlock    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/app/airlock/business_logic.py", line 198, in get_contents_url
airlock    |     renderer = self.get_renderer(relpath)
airlock    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/app/airlock/business_logic.py", line 205, in get_renderer
airlock    |     return renderer_class.from_file(
airlock    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/app/airlock/renderers.py", line 56, in from_file
airlock    |     stream=abspath.open(cls.open_mode),
airlock    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    |   File "/usr/lib/python3.11/pathlib.py", line 1044, in open
airlock    |     return io.open(self, mode, buffering, encoding, errors, newline)
airlock    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airlock    | IsADirectoryError: [Errno 21] Is a directory: '/workspaces/benbc-test/empty_subdir'
```
