### ISSUE TITLE
just `load-example-data` no longer works

### ISSUE THREAD

**Issue by evansd** [opensafely-core/airlock#359]
This is the commit at which it breaks:
https://github.com/opensafely-core/airlock/commit/ad3488bc940c2eefc58d6f4a10e3c62337bc61bc

I guess this is because we now assume every workspace has a manifest and therefore the migration script that used to run on the old example data no longer works.

I think we should probably add this command to CI. It's hard to test it fully because it would still be possible for it to run without error but not correctly set up the example data. But I think just confirming that it runs without blowing up would be enough for now.

For reference the full error is:
```
$ just load-example-data

Archive:  /tmp/tmp.9LzDkKKZOO
cat scripts/manifests.py | $BIN/python manage.py shell
Writing manifest.json and creating repo for workspace example-workspace
Traceback (most recent call last):
  File "/home/dave/projects/ebmdatalab/airlock/manage.py", line 27, in <module>
    main()
  File "/home/dave/projects/ebmdatalab/airlock/manage.py", line 23, in main
    execute_from_command_line(sys.argv)
  File "/home/dave/.virtualenvs/ebm-airlock/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/dave/.virtualenvs/ebm-airlock/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dave/.virtualenvs/ebm-airlock/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dave/.virtualenvs/ebm-airlock/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-airlock/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 127, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 10, in <module>
  File "/home/dave/projects/ebmdatalab/airlock/tests/factories.py", line 169, in create_repo
    workspace = ensure_workspace(workspace)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/ebmdatalab/airlock/tests/factories.py", line 48, in ensure_workspace
    return create_workspace(workspace_or_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/ebmdatalab/airlock/tests/factories.py", line 156, in create_workspace
    return bll.get_workspace(name, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/ebmdatalab/airlock/airlock/business_logic.py", line 951, in get_workspace
    return Workspace.from_directory(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/ebmdatalab/airlock/airlock/business_logic.py", line 246, in from_directory
    raise BusinessLogicLayer.ManifestFileError(
airlock.business_logic.BusinessLogicLayer.ManifestFileError: /home/dave/projects/ebmdatalab/airlock/workdir/workspaces/example-workspace/metadata/manifest.json does not exist
error: Recipe `manifests` failed on line 210 with exit code 1
```

**Comment by bloodearnest** [comment]
fixed in #371
